const ANIMATION_NAME = {

    //
    // ==============================   Male   ==============================
    //

    squats_male: require('../../data/local-storage/animations/01_Squats_male.webp'),
    legSwingRightLeg_male: require('../../data/local-storage/animations/02_Leg_Swing_R_male.webp'),
    legSwingLeftLeg_male: require('../../data/local-storage/animations/02_Leg_Swing_L_male.webp'),
    gluteBridge_male: require('../../data/local-storage/animations/03_Glute_Bridge_male.webp'),
    innerThighLiftRightLeg_male: require('../../data/local-storage/animations/04_Inner_Thigh_Lift_R_male.webp'),
    innerThighLiftLeftLeg_male: require('../../data/local-storage/animations/04_Inner_Thigh_Lift_L_male.webp'),
    sideLegLiftRightLeg_male: require('../../data/local-storage/animations/05_Side_Leg_Lift_R_male.webp'),
    sideLegLiftLeftLeg_male: require('../../data/local-storage/animations/05_Side_Leg_Lift_L_male.webp'),
    gluteKickbacksRightLeg_male: require('../../data/local-storage/animations/06_Glute_Kickbacks_R_male.webp'),
    gluteKickbacksLeftLeg_male: require('../../data/local-storage/animations/06_Glute_Kickbacks_L_male.webp'),
    pulsingLungesLeftLeg_male: require('../../data/local-storage/animations/07_Pulsing_Lunges_L_male.webp'),
    pulsingLungesRightLeg_male: require('../../data/local-storage/animations/07_Pulsing_Lunges_R_male.webp'),
    marchingHip_male: require('../../data/local-storage/animations/08_Marching_Hip_male.webp'),
    singleLegHipThrustersRightLeg_male: require('../../data/local-storage/animations/09_Single_Leg_Hip_Thrusters_R_male.webp'),
    singleLegHipThrustersLeftLeg_male: require('../../data/local-storage/animations/09_Single_Leg_Hip_Thrusters_L_male.webp'),
    oneLegBridgeRightLeg_male: require('../../data/local-storage/animations/10_One_Leg_Bridge_R_male.webp'),
    oneLegBridgeLeftLeg_male: require('../../data/local-storage/animations/10_One_Leg_Bridge_L_male.webp'),
    singleLegDeadliftRightLeg_male: require('../../data/local-storage/animations/11_Single_Leg_Deadlift_R_male.webp'),
    singleLegDeadliftLeftLeg_male: require('../../data/local-storage/animations/11_Single_Leg_Deadlift_L_male.webp'),
    plank_male: require('../../data/local-storage/animations/12_Planks_male.webp'),
    basicCrunches_male: require('../../data/local-storage/animations/13_Basic_Crunches_male.webp'),
    mountainClimbers_male: require('../../data/local-storage/animations/14_Mountain_Climbers_male.webp'),
    rollup_male: require('../../data/local-storage/animations/15_Rollup_male.webp'),
    // windshield_male: require('../../data/local-storage/animations/_male.webp'), // TODO: N/A
    reverseCrunchStraight_male: require('../../data/local-storage/animations/17_Reverse_Crunch_Straight_male.webp'),
    commandos_male: require('../../data/local-storage/animations/19_Commandos_male.webp'),
    doubleLegLift_male: require('../../data/local-storage/animations/20_Double_Leg_Lift_male.webp'),
    doubleLegReach_male: require('../../data/local-storage/animations/21_Double_Leg_Reach_male.webp'),
    armPlankWithKnees_male: require('../../data/local-storage/animations/22_Arm_Plank_with_Knees_male.webp'),
    boatPose_male: require('../../data/local-storage/animations/23_Boat_pose_male.webp'),
    reverseJackKnives_male: require('../../data/local-storage/animations/24_Jack_Knives_male.webp'),
    cobraPushUp_male: require('../../data/local-storage/animations/25_Cobra_Push_Up_male.webp'),
    oneArmPushUpRightArm_male: require('../../data/local-storage/animations/26_One_Arm_Push_Up_R_male.webp'),
    oneArmPushUpLeftArm_male: require('../../data/local-storage/animations/26_One_Arm_Push_Up_L_male.webp'),
    handPlankReaches_male: require('../../data/local-storage/animations/27_Hand_Plank_Reaches_male.webp'),
    plankRightSide_male: require('../../data/local-storage/animations/28_Plank_Hip_Dips_R_male.webp'), // 28_Side_Plank_R_male
    plankLeftSide_male: require('../../data/local-storage/animations/28_Plank_Hip_Dips_L_male.webp'), // 28_Side_Plank_L_male
    kneePushUps_male: require('../../data/local-storage/animations/29_Knee_Push_Ups_male.webp'),
    shouldPushUps_male: require('../../data/local-storage/animations/30_Push_Ups_male.webp'),
    pushUp_male: require('../../data/local-storage/animations/30_Push_Ups_male.webp'),
    bentOverRow_male: require('../../data/local-storage/animations/31_Bent_Over_Row_male.webp'),
    lateralRaises_male: require('../../data/local-storage/animations/32_Lateral_Raise_male.webp'),
    tricepExtensionRight_male: require('../../data/local-storage/animations/33_Tricep_Extension_R_male.webp'),
    tricepExtensionLeft_male: require('../../data/local-storage/animations/33_Tricep_Extension_L_male.webp'),
    dumbellSwing_male: require('../../data/local-storage/animations/34_Dumbell_Swing_male.webp'),
    squatAndCurl_male: require('../../data/local-storage/animations/35_Squat_and_Curl_male.webp'),
    tricepKickback_male: require('../../data/local-storage/animations/36_Tricep_Kickback_male.webp'),
    // plankHipDips_male: require('../../data/local-storage/animations/_male.webp'), // TODO: N/A
    crabWalk_male: require('../../data/local-storage/animations/38_Crab_Walks_male.webp'),
    spineStretch_male: require('../../data/local-storage/animations/39_Spine_Stretch_male.webp'),
    lyingKneeHug_male: require('../../data/local-storage/animations/40_Lying_Knee_Hug_R_male.webp'), // FIXME
    woodpecker_male: require('../../data/local-storage/animations/41_Woodpecker_male.webp'),
    rollingOver_male: require('../../data/local-storage/animations/42_Rolling_over_male.webp'),
    runnersCrunch_male: require('../../data/local-storage/animations/43_Runner_s_Crunch_male.webp'),
    theFounder_male: require('../../data/local-storage/animations/44_The_Founder_male.webp'),
    // kneelingObliqueCrunch_male: require('../../data/local-storage/animations/_male.webp'), // TODO: N/A
    mcGillCurlUpRight_male: require('../../data/local-storage/animations/46_McGill_Curl_Up_R_male.webp'),
    mcGillCurlUpLeft_male: require('../../data/local-storage/animations/46_McGill_Curl_Up_L_male.webp'),
    birdDogRight_male: require('../../data/local-storage/animations/47_Bird_Dog_R_male.webp'),
    birdDogLeft_male: require('../../data/local-storage/animations/47_Bird_Dog_L_male.webp'),
    tricepDip_male: require('../../data/local-storage/animations/57_Tricep_Dip_male.webp'),
    wallSit_male: require('../../data/local-storage/animations/58_Wall_sit_male.webp'),
    jumpingJacks_male: require('../../data/local-storage/animations/59_Jumping_Jacks_male.webp'),
    burpees_male: require('../../data/local-storage/animations/60_Burpees_male.webp'),

    //
    // ==============================   Female   ==============================
    //

    squats_female: require('../../data/local-storage/animations/01_Squats_female.webp'),
    legSwingRightLeg_female: require('../../data/local-storage/animations/02_Leg_Swing_R_female.webp'),
    legSwingLeftLeg_female: require('../../data/local-storage/animations/02_Leg_Swing_L_female.webp'),
    gluteBridge_female: require('../../data/local-storage/animations/03_Glute_Bridge_female.webp'),
    innerThighLiftRightLeg_female: require('../../data/local-storage/animations/04_Inner_Thigh_Lift_R_female.webp'),
    innerThighLiftLeftLeg_female: require('../../data/local-storage/animations/04_Inner_Thigh_Lift_L_female.webp'),
    sideLegLiftRightLeg_female: require('../../data/local-storage/animations/05_Side_Leg_Lift_R_female.webp'),
    sideLegLiftLeftLeg_female: require('../../data/local-storage/animations/05_Side_Leg_Lift_L_female.webp'),
    gluteKickbacksRightLeg_female: require('../../data/local-storage/animations/06_Glute_Kickbacks_R_female.webp'),
    gluteKickbacksLeftLeg_female: require('../../data/local-storage/animations/06_Glute_Kickbacks_L_female.webp'),
    pulsingLungesLeftLeg_female: require('../../data/local-storage/animations/07_Pulsing_Lunges_L_female.webp'),
    pulsingLungesRightLeg_female: require('../../data/local-storage/animations/07_Pulsing_Lunges_R_female.webp'),
    marchingHip_female: require('../../data/local-storage/animations/08_Marching_Hip_female.webp'),
    singleLegHipThrustersRightLeg_female: require('../../data/local-storage/animations/09_Single_Leg_Hip_Thrusters_R_female.webp'),
    singleLegHipThrustersLeftLeg_female: require('../../data/local-storage/animations/09_Single_Leg_Hip_Thrusters_L_female.webp'),
    oneLegBridgeRightLeg_female: require('../../data/local-storage/animations/10_One_Leg_Bridge_R_female.webp'),
    oneLegBridgeLeftLeg_female: require('../../data/local-storage/animations/10_One_Leg_Bridge_L_female.webp'),
    singleLegDeadliftRightLeg_female: require('../../data/local-storage/animations/11_Single_Leg_Deadlift_R_female.webp'),
    singleLegDeadliftLeftLeg_female: require('../../data/local-storage/animations/11_Single_Leg_Deadlift_L_female.webp'),
    plank_female: require('../../data/local-storage/animations/12_Planks_female.webp'),
    basicCrunches_female: require('../../data/local-storage/animations/13_Basic_Crunches_female.webp'),
    mountainClimbers_female: require('../../data/local-storage/animations/14_Mountain_Climbers_female.webp'),
    rollup_female: require('../../data/local-storage/animations/15_Rollup_female.webp'),
    // windshield_female: require('../../data/local-storage/animations/_female.webp'), // TODO: N/A
    reverseCrunchStraight_female: require('../../data/local-storage/animations/17_Reverse_Crunch_Straight_female.webp'),
    commandos_female: require('../../data/local-storage/animations/19_Commandos_female.webp'),
    doubleLegLift_female: require('../../data/local-storage/animations/20_Double_Leg_Lift_female.webp'),
    doubleLegReach_female: require('../../data/local-storage/animations/21_Double_Leg_Reach_female.webp'),
    armPlankWithKnees_female: require('../../data/local-storage/animations/22_Arm_Plank_with_Knees_female.webp'),
    boatPose_female: require('../../data/local-storage/animations/23_Boat_pose_female.webp'),
    reverseJackKnives_female: require('../../data/local-storage/animations/24_Jack_Knives_female.webp'),
    cobraPushUp_female: require('../../data/local-storage/animations/25_Cobra_Push_Up_female.webp'),
    oneArmPushUpRightArm_female: require('../../data/local-storage/animations/26_One_Arm_Push_Up_R_female.webp'),
    oneArmPushUpLeftArm_female: require('../../data/local-storage/animations/26_One_Arm_Push_Up_L_female.webp'),
    handPlankReaches_female: require('../../data/local-storage/animations/27_Hand_Plank_Reaches_female.webp'),
    plankRightSide_female: require('../../data/local-storage/animations/28_Plank_Hip_Dips_R_female.webp'),
    plankLeftSide_female: require('../../data/local-storage/animations/28_Plank_Hip_Dips_L_female.webp'),
    kneePushUps_female: require('../../data/local-storage/animations/29_Knee_Push_Ups_female.webp'),
    shouldPushUps_female: require('../../data/local-storage/animations/30_Push_Ups_female.webp'),
    pushUp_female: require('../../data/local-storage/animations/30_Push_Ups_female.webp'),
    bentOverRow_female: require('../../data/local-storage/animations/31_Bent_Over_Row_female.webp'),
    lateralRaises_female: require('../../data/local-storage/animations/32_Lateral_Raise_female.webp'),
    tricepExtensionRight_female: require('../../data/local-storage/animations/33_Tricep_Extension_R_female.webp'),
    tricepExtensionLeft_female: require('../../data/local-storage/animations/33_Tricep_Extension_L_female.webp'),
    dumbellSwing_female: require('../../data/local-storage/animations/34_Dumbell_Swing_female.webp'),
    squatAndCurl_female: require('../../data/local-storage/animations/35_Squat_and_Curl_female.webp'),
    tricepKickback_female: require('../../data/local-storage/animations/36_Tricep_Kickback_female.webp'),
    // plankHipDips_female: require('../../data/local-storage/animations/_female.webp'), // TODO: N/A
    crabWalk_female: require('../../data/local-storage/animations/38_Crab_Walks_female.webp'),
    spineStretch_female: require('../../data/local-storage/animations/39_Spine_Stretch_female.webp'),
    lyingKneeHug_female: require('../../data/local-storage/animations/40_Lying_Knee_Hug_R_female.webp'), // FIXME
    woodpecker_female: require('../../data/local-storage/animations/41_Woodpecker_female.webp'),
    rollingOver_female: require('../../data/local-storage/animations/42_Rolling_over_female.webp'),
    runnersCrunch_female: require('../../data/local-storage/animations/43_Runner_s_Crunch_female.webp'),
    theFounder_female: require('../../data/local-storage/animations/44_The_Founder_female.webp'),
    // kneelingObliqueCrunch_female: require('../../data/local-storage/animations/_female.webp'), // TODO: N/A
    mcGillCurlUpRight_female: require('../../data/local-storage/animations/46_McGill_Curl_Up_R_female.webp'),
    mcGillCurlUpLeft_female: require('../../data/local-storage/animations/46_McGill_Curl_Up_L_female.webp'),
    birdDogRight_female: require('../../data/local-storage/animations/47_Bird_Dog_R_female.webp'),
    birdDogLeft_female: require('../../data/local-storage/animations/47_Bird_Dog_L_female.webp'),
    tricepDip_female: require('../../data/local-storage/animations/57_Tricep_Dip_female.webp'),
    wallSit_female: require('../../data/local-storage/animations/58_Wall_sit_female.webp'),
    jumpingJacks_female: require('../../data/local-storage/animations/59_Jumping_Jacks_female.webp'),
    burpees_female: require('../../data/local-storage/animations/60_Burpees_female.webp'),
};

export default {
    getAnimationSource(exerciseName, gender) {
        return ANIMATION_NAME[`${exerciseName}_${gender}`] || null;
    }
}